### ISSUE TITLE
usbutils package may not be installed in some distros.

### ISSUE THREAD

**Issue by raxetul** [ismailtasdelen/PyUSB#1]
A PyPi usb library should be used instead.
Also staying away calling external commands will be good always. Using APIs is better.
https://github.com/ismailtasdelen/PyUSB/blob/944a04588c2ca0e97fdfe2aa4eb51e4e74632fc7/usb_device.py#L7

**Comment by ismailtasdelen** [comment]
Thanks feedback :+1:
